### PR TITLE
Fix technology usage messages

### PR DESCRIPTION
**Pull request by jmle**

### CODE REVIEW

**Comment by shawn-hurley** [comment]
IIUC, this is fixing the case when technology rules are supposed to be just for tagging, but they have a message so now we are also getting violations that we should not. Is this correct?

**Review by shawn-hurley — APPROVED** [review]
if my understanding in the previous comment was correct, then this LGTM

**Comment by jmle** [comment]
@shawn-hurley that's correct. Some rules were left out... I think this should cover all.

**Comment by shawn-hurley** [comment]
@pranavgaikwad you are out on PTO, going to merge this now and if there is something way off just revert when you get back

**Pull request merged**
